# Generated by Django 4.0.4 on 2022-07-25 16:35

from django.db import migrations, models
import numbers


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_delete_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='id',
            field=models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False, verbose_name=numbers.Integral),
        ),
    ]
